### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by andrfgs** [ondrejbudai/hidviz#29] opened 2020-06-30 04:17 UTC
I can't build the program, it seems to complain about a missing header (`#include <libhidx/Interface.hh>`). I have already installed libhidx but there's no `Interface.hh` file in libhidx source. Is the branch master considered stable?

I have built and installed libhidx just fine (through `make install`).

**Comment by ondrejbudai** [comment] 2020-06-30 12:04
Thanks for the bug report! Can you specify on which distro does this happen?

**Comment by andrfgs** [comment] 2020-06-30 16:11
I'm using Arch Linux. 

Nevermind, I found out the interface file. Is there any reason CMake would not locate the include files? I built the libhidx the following way:
1. Checked out from libhidx
2. Ran cmake .
3. Ran make
4. Ran make install

**Comment by ondrejbudai** [comment] 2020-06-30 16:17
I have no idea. Where does `make install` put those headers? Can you find them?

BTW, you can install `hidviz` from AUR.

**Comment by ondrejbudai** [comment] 2020-06-30 16:23
I looked into Fedora spec file and to `PKGBUILD` in AUR and you should be able to install hidviz like this:

1. clone `hidviz` repo recursively
2. `mkdir build && cd build`
3. `cmake ..`
4. `make`
5. `sudo make install`

`PKGBUILD` in AUR actually runs the following commands, not sure if these explicit paths are needed:

```
prepare() {
        cd "${pkgname}-${pkgver}"
        mkdir -p build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ..
}

build() {
        cd "${pkgname}-${pkgver}"/build
        make
}

package() {
        cd "${pkgname}-${pkgver}"/build
        make DESTDIR="${pkgdir}" install
}
```

**Comment by andrfgs** [comment] 2020-06-30 16:32
The AUR package is also broken, that's what I tried in the first place. It reports undefined references to certain symbols:

<details>
  <summary>build() make output</summary>
  
  ```bash
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceSelector.cc.o: in function `hidviz::DeviceSelector::DeviceSelector(libhidx::LibHidx&)':
DeviceSelector.cc:(.text+0x4d): undefined reference to `vtable for hidviz::DeviceSelector'
/usr/bin/ld: DeviceSelector.cc:(.text+0x5f): undefined reference to `vtable for hidviz::DeviceSelector'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceSelector.cc.o: in function `hidviz::DeviceSelector::~DeviceSelector()':
DeviceSelector.cc:(.text+0x205): undefined reference to `vtable for hidviz::DeviceSelector'
/usr/bin/ld: DeviceSelector.cc:(.text+0x217): undefined reference to `vtable for hidviz::DeviceSelector'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceSelector.cc.o: in function `hidviz::DeviceSelector::selectDevice()':
DeviceSelector.cc:(.text+0x635): undefined reference to `hidviz::DeviceSelector::deviceSelected(libhidx::Interface&)'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceSelector.cc.o: in function `hidviz::DeviceSelector::reloadDevices()':
DeviceSelector.cc:(.text+0x7a2): undefined reference to `hidviz::DeviceSelector::listCleared()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/Window.cc.o: in function `hidviz::Window::Window(QWidget*)':
Window.cc:(.text+0x5c): undefined reference to `vtable for hidviz::Window'
/usr/bin/ld: Window.cc:(.text+0x71): undefined reference to `vtable for hidviz::Window'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/Window.cc.o: in function `hidviz::Window::~Window()':
Window.cc:(.text+0x74d): undefined reference to `vtable for hidviz::Window'
/usr/bin/ld: Window.cc:(.text+0x75f): undefined reference to `vtable for hidviz::Window'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/Window.cc.o: in function `hidviz::Window::openDeviceSelector()':
Window.cc:(.text+0x8cf): undefined reference to `hidviz::DeviceSelector::deviceSelected(libhidx::Interface&)'
/usr/bin/ld: Window.cc:(.text+0x937): undefined reference to `hidviz::DeviceSelector::listCleared()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/Window.cc.o: in function `QMetaObject::Connection QObject::connect<void (hidviz::DeviceSelector::*)(libhidx::Interface&), void (hidviz::Window::*)(libhidx::Interface&)>(QtPrivate::FunctionPointer<void (hidviz::DeviceSelector::*)(libhidx::Interface&)>::Object const*, void (hidviz::DeviceSelector::*)(libhidx::Interface&), QtPrivate::FunctionPointer<void (hidviz::Window::*)(libhidx::Interface&)>::Object const*, void (hidviz::Window::*)(libhidx::Interface&), Qt::ConnectionType)':
Window.cc:(.text._ZN7QObject7connectIMN6hidviz14DeviceSelectorEFvRN7libhidx9InterfaceEEMNS1_6WindowEFvS5_EEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESF_PKNSE_IT0_E6ObjectESK_N2Qt14ConnectionTypeE[_ZN7QObject7connectIMN6hidviz14DeviceSelectorEFvRN7libhidx9InterfaceEEMNS1_6WindowEFvS5_EEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESF_PKNSE_IT0_E6ObjectESK_N2Qt14ConnectionTypeE]+0x87): undefined reference to `hidviz::DeviceSelector::staticMetaObject'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/Window.cc.o: in function `QMetaObject::Connection QObject::connect<void (hidviz::DeviceSelector::*)(), void (hidviz::Window::*)()>(QtPrivate::FunctionPointer<void (hidviz::DeviceSelector::*)()>::Object const*, void (hidviz::DeviceSelector::*)(), QtPrivate::FunctionPointer<void (hidviz::Window::*)()>::Object const*, void (hidviz::Window::*)(), Qt::ConnectionType)':
Window.cc:(.text._ZN7QObject7connectIMN6hidviz14DeviceSelectorEFvvEMNS1_6WindowEFvvEEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESC_PKNSB_IT0_E6ObjectESH_N2Qt14ConnectionTypeE[_ZN7QObject7connectIMN6hidviz14DeviceSelectorEFvvEMNS1_6WindowEFvvEEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESC_PKNSB_IT0_E6ObjectESH_N2Qt14ConnectionTypeE]+0x87): undefined reference to `hidviz::DeviceSelector::staticMetaObject'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/ControlWidget.cc.o: in function `hidviz::hid::ControlWidget::ControlWidget(libhidx::hid::Control*, QWidget*)':
ControlWidget.cc:(.text+0x3c): undefined reference to `vtable for hidviz::hid::ControlWidget'
/usr/bin/ld: ControlWidget.cc:(.text+0x4e): undefined reference to `vtable for hidviz::hid::ControlWidget'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/ControlWidget.cc.o: in function `hidviz::hid::ControlWidget::initUsages()':
ControlWidget.cc:(.text+0x4ab): undefined reference to `hidviz::hid::ControlWidget::dataUpdated()'
/usr/bin/ld: ControlWidget.cc:(.text+0x4bb): undefined reference to `hidviz::hid::UsageWidget::dataUpdated()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/ControlWidget.cc.o: in function `QMetaObject::Connection QObject::connect<void (hidviz::hid::UsageWidget::*)(), void (hidviz::hid::ControlWidget::*)()>(QtPrivate::FunctionPointer<void (hidviz::hid::UsageWidget::*)()>::Object const*, void (hidviz::hid::UsageWidget::*)(), QtPrivate::FunctionPointer<void (hidviz::hid::ControlWidget::*)()>::Object const*, void (hidviz::hid::ControlWidget::*)(), Qt::ConnectionType)':
ControlWidget.cc:(.text._ZN7QObject7connectIMN6hidviz3hid11UsageWidgetEFvvEMNS2_13ControlWidgetEFvvEEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESD_PKNSC_IT0_E6ObjectESI_N2Qt14ConnectionTypeE[_ZN7QObject7connectIMN6hidviz3hid11UsageWidgetEFvvEMNS2_13ControlWidgetEFvvEEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESD_PKNSC_IT0_E6ObjectESI_N2Qt14ConnectionTypeE]+0x87): undefined reference to `hidviz::hid::UsageWidget::staticMetaObject'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `hidviz::DeviceView::DeviceView(libhidx::Interface&, QWidget*)::{lambda()#1}::operator()() const':
DeviceView.cc:(.text+0x17): undefined reference to `hidviz::DeviceView::dataRead()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `hidviz::DeviceView::DeviceView(libhidx::Interface&, QWidget*)':
DeviceView.cc:(.text+0x87): undefined reference to `vtable for hidviz::DeviceView'
/usr/bin/ld: DeviceView.cc:(.text+0x9c): undefined reference to `vtable for hidviz::DeviceView'
/usr/bin/ld: DeviceView.cc:(.text+0x1d9): undefined reference to `hidviz::DeviceView::dataRead()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `hidviz::DeviceView::addItem(libhidx::hid::Item*, hidviz::hid::ItemWidget*) [clone .localalias]':
DeviceView.cc:(.text+0x622): undefined reference to `hidviz::hid::ControlWidget::dataUpdated()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `hidviz::DeviceView::updateData()':
DeviceView.cc:(.text+0x824): undefined reference to `typeinfo for hidviz::hid::ControlWidget'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `hidviz::DeviceView::~DeviceView()':
DeviceView.cc:(.text+0x8a9): undefined reference to `vtable for hidviz::DeviceView'
/usr/bin/ld: DeviceView.cc:(.text+0x8bb): undefined reference to `vtable for hidviz::DeviceView'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `QMetaObject::Connection QObject::connect<void (hidviz::DeviceView::*)(), void (hidviz::DeviceView::*)()>(QtPrivate::FunctionPointer<void (hidviz::DeviceView::*)()>::Object const*, void (hidviz::DeviceView::*)(), QtPrivate::FunctionPointer<void (hidviz::DeviceView::*)()>::Object const*, void (hidviz::DeviceView::*)(), Qt::ConnectionType)':
DeviceView.cc:(.text._ZN7QObject7connectIMN6hidviz10DeviceViewEFvvES4_EEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectES9_PKNS8_IT0_E6ObjectESE_N2Qt14ConnectionTypeE[_ZN7QObject7connectIMN6hidviz10DeviceViewEFvvES4_EEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectES9_PKNS8_IT0_E6ObjectESE_N2Qt14ConnectionTypeE]+0x87): undefined reference to `hidviz::DeviceView::staticMetaObject'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/DeviceView.cc.o: in function `QMetaObject::Connection QObject::connect<void (hidviz::hid::ControlWidget::*)(), void (hidviz::DeviceView::*)()>(QtPrivate::FunctionPointer<void (hidviz::hid::ControlWidget::*)()>::Object const*, void (hidviz::hid::ControlWidget::*)(), QtPrivate::FunctionPointer<void (hidviz::DeviceView::*)()>::Object const*, void (hidviz::DeviceView::*)(), Qt::ConnectionType)':
DeviceView.cc:(.text._ZN7QObject7connectIMN6hidviz3hid13ControlWidgetEFvvEMNS1_10DeviceViewEFvvEEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESD_PKNSC_IT0_E6ObjectESI_N2Qt14ConnectionTypeE[_ZN7QObject7connectIMN6hidviz3hid13ControlWidgetEFvvEMNS1_10DeviceViewEFvvEEEN11QMetaObject10ConnectionEPKN9QtPrivate15FunctionPointerIT_E6ObjectESD_PKNSC_IT0_E6ObjectESI_N2Qt14ConnectionTypeE]+0x87): undefined reference to `hidviz::hid::ControlWidget::staticMetaObject'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/UsageWidget.cc.o: in function `hidviz::hid::UsageWidget::UsageWidget(libhidx::hid::Usage&, QWidget*)':
UsageWidget.cc:(.text+0x49): undefined reference to `vtable for hidviz::hid::UsageWidget'
/usr/bin/ld: UsageWidget.cc:(.text+0x5b): undefined reference to `vtable for hidviz::hid::UsageWidget'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/UsageWidget.cc.o: in function `hidviz::hid::UsageWidget::initOutput()::{lambda()#2}::operator()() const':
UsageWidget.cc:(.text+0x2b6): undefined reference to `hidviz::hid::UsageWidget::dataUpdated()'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/UsageWidget.cc.o: in function `hidviz::hid::UsageWidget::~UsageWidget()':
UsageWidget.cc:(.text+0x707): undefined reference to `vtable for hidviz::hid::UsageWidget'
/usr/bin/ld: UsageWidget.cc:(.text+0x719): undefined reference to `vtable for hidviz::hid::UsageWidget'
/usr/bin/ld: CMakeFiles/hidviz.dir/src/hid/UsageWidget.cc.o: in function `auto hidviz::hid::UsageWidget::initOutput()::{lambda(auto:1)#1}::operator()<bool>(bool) const':
UsageWidget.cc:(.text+0xd77): undefined reference to `hidviz::hid::UsageWidget::dataUpdated()'
collect2: error: ld returned 1 exit status
make[2]: *** [hidviz/CMakeFiles/hidviz.dir/build.make:315: hidviz/hidviz] Erro 1
make[1]: *** [CMakeFiles/Makefile2:198: hidviz/CMakeFiles/hidviz.dir/all] Erro 2

  ```
</details>

Anyways, I ran those exact commands and it didn't work. By the way this installed `libhidx_server_daemon` on `/usr/local/libexec/` is this the intended library?

**Comment by ondrejbudai** [comment] 2020-06-30 16:39
Yes, the daemon should be installed in this location.

**Comment by ondrejbudai** [comment] 2020-06-30 16:52
I think this is actually duplicate of #27. The fix proposed in #27 fixed the issues on arch for me. I updated #28 and if Travis is green, I will merge it.

**Comment by andrfgs** [comment] 2020-06-30 16:53
Sorry for all of this extra work. By the way, the AUR has the dependencies wrong. It doesn't install asio or protobuf by default.

Thank you in advance for all the support!

**Comment by ondrejbudai** [comment] 2020-06-30 16:57
Fixed by #28 

@andrfgs I have no idea how AUR works. If you can fix it, it would be really awesome. :-)

**Closed as completed by ondrejbudai** 2020-06-30 16:57 UTC

**Comment by andrfgs** [comment] 2020-06-30 17:05
It now complains about a missing `Buffer.pb.h`. I have installed protobuf. Is this a special version of protobuf?

**Comment by ondrejbudai** [comment] 2020-06-30 17:35
I ran `pacman -Sy protobuf` and it worked. Do you have a different `protobuf`?

**Comment by andrfgs** [comment] 2020-06-30 17:39
No I have that one installed. I double checked that exact version and it asked me if I wished to reinstall it. Maybe this is a problem with my libhix. Did you also update the other repository?

**Comment by andrfgs** [comment] 2020-06-30 17:58
I only built `libhidx` when I try to build `libhidx_server` it fails:

```bash
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/libusb-1.0.so
CMake Error at CMakeLists.txt:39 (get_target_property):
  get_target_property() called with non-existent target "hidx".


CMake Error at CMakeLists.txt:41 (if):
  if given arguments:

    "NOT" "WIN32" "AND" "STREQUAL" "SHARED_LIBRARY"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/andre/hidviz/libhidx/libhidx_server/CMakeFiles/CMakeOutput.log".
See also "/home/andre/hidviz/libhidx/libhidx_server/CMakeFiles/CMakeError.log".

```

**Comment by ondrejbudai** [comment] 2020-06-30 18:00
Hmm... Have you tried running the exact same commands like in the README?

https://github.com/ondrejbudai/hidviz#12-clone-and-prepare-out-of-source-build

**Comment by ondrejbudai** [comment] 2020-06-30 18:04
You cannot use `cmake` on `hidviz/libhidx/libhidx_server`. `cmake` can be run in the root directory or in the `libhidx` directory. As `libhidx` is basically useless on its own, just use the same procedure as it's in the README, it should work, I just tested it in a container. :)

Also, I suggest using out of source build, in source one is untested.

**Comment by andrfgs** [comment] 2020-06-30 18:07
Nevermind, I deleted that cause I found out that. Nevermind I said that, I just stupidely tried to compile that in cmake and then understood I was doing it wrong.

Regardless, the libhidx is installed in /usr/local just fine. The problem now is when making hidviz which reports file `Buffer.pb.h` is missing. It wont let me compile. I already tried recloning the repository again.

By the way, I still have to manually copy the include files to the folder, not sure if this is normal but might be intended I don't know.

**Comment by andrfgs** [comment] 2020-06-30 18:11
It turns out the protocol buffer compiler is not working when making this project. How do I force it to work?

**Comment by ondrejbudai** [comment] 2020-06-30 18:11
And you did the exact same steps as in the README? Can you post a whole log? Preferably everything from the initial `git clone --recursive`.

**Comment by andrfgs** [comment] 2020-06-30 18:17
Ok it was my fault. I was building from the `build` folder using `cmake ../hidviz` instead of using `cmake ..`, so CMake was just making the hidviz module probably causing linking problems in libhidx. Sorry for my mistake and thank you for all the support.
